openapi: 3.0.3
info:
  title: Recept.io 1.0
  description: Something crazx
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
paths:
  /create:
    summary: Create a  Recipe 
    description: 'Create a Recipe
    post:
      summary: Create a  recipe 
      description: Create a  Recipe 
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Recipe"
      responses:
        default:
          description: Default error sample response
  /delete/{id}:
    summary: Delete a Recipe
    description: Delete a Recipe
    delete:
      summary: Delete Recipe
      description: Delete Recipe
      parameters:
        - name: "id"
          in: "path"
          description: "Id of source-template"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Recipe delete successfully
        "400":
          description: Invalid formatted Object
        "403":
          description: Permission to delete Recipe denied
        "406":
          description: Must not change the MIME type of the resource
        "500":
          description: An unexpected server error occurred

  /update:
    summary: Update a Recipe
    description: Update a Recipe
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Recipe"
      responses:
        "200":
          description: Recipe updated successfully
        "400":
          description: Invalid formatted Object
        "403":
          description: Permission to update Recipe denied
        "406":
          description: Must not change the MIME type of the resource
        "500":
          description: An unexpected server error occurred
  /Recipe/{id}:
    summary: Get Recipe
    description: Get Recipe
    get:
      summary: Get  Recipe
      description: Get  Recipe
      parameters:
        - name: "id"
          in: "path"
          description: "Id of source-template"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Recipe successfully returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recipe"

        "403":
          description: Permission to get a Recipe denied
        "406":
          description: Must not change the MIME type of the resource
        "500":
          description: An unexpected server error occurred
  /Recipe:
    summary: Get All Recipe
    description: Get All Recipe
    get:
      summary: Get All Recipe
      description: Get All Recipe
      responses: 
        "200":
          description: Recipe successfully returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Recipe"

        "403":
          description: Permission to get a Recipe denied
        "406":
          description: Must not change the MIME type of the resource
        "500":
          description: An unexpected server error occurred
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: string
          format: UUID4
          example: e3c2081e-8efa-4a30-8a2a-a9f44256180f
        title:
          type: string
          example: 'Pizza'
        author:
          type: string
          example: 'emma'
        ingredients:
          type: array
          items: 
            $ref: "#/components/schemas/Ingredients"
          example: 'Pizza'  
        timestamp:
          type: string
          format: date-time
    Ingredients:
      type: object
      properties:
        id:
          type: string
          format: UUID4
          example: e3c2081e-8efa-4a30-8a2a-a9f44256180f
        name:
          type: string
          example: 'Pizza'
        quantity:
          type: string
          example: '2.2 löffel'
 
    